### ISSUE TITLE
What is the purpose of FileNodeCollection?

### ISSUE THREAD

**Issue by billziss-gh** [yogendersolanki91/winfsp#13]
What is the purpose of `FileNodeCollection` in `src/dotnet/fileNode.*`?

I see some of its methods (`GetFileOpenContext`) being used from `WinFspFunc::*`, but I am unclear to why this is needed. Can you please elaborate?

**Comment by yogendersolanki91** [comment]
In native WinFsp implementation you are using FileContext which is an address. It provide you file operation context across the file handle lifetime. In C# , we can do this either marshaling a data structure or using a dictionary which create a context whenever you open an new handle. In short two get the file handle context (open/create) I am using this because I cannot access a fixed address in .NET because there is no concept of memory address in .NET. I think cost of lookup in dictionary will be less compared to marshaling a data-structure.  It basically stores a FileOpenContext per open operation and FileOpenContext has one FileNode which has  field which can be used UserMode fileystem to assign and use arbitrary data structure.  


Repersents a data structure FileHandle which is similart to FIleContext
```cpp
	public ref class FileOpenContext {
		FileNode^ NodeVal;
		UINT64 IdVal;
	public:
		Object^ UserContext2;
		GET_PROPERTY(FileNode^, Node, NodeVal)
		GET_PROPERTY(UINT64, NodeId, IdVal)
		FileOpenContext(FileNode^ node, UINT id) {
			NodeVal = node;
			IdVal = id;
		}
	}
```

```cpp
public ref class FileNode {
		FileInfo^ info;		
		String^ fn;
	    INT64 RefCount;
		
	public:
		SecuirtyDescriptor^ Security;
		Object^ UserContext; //User mode file system can assign its own arbitrary data structure using this field
		GET_PROPERTY(String^, FileName, fn)
		GET_PROPERTY(INT64, OpenCount, RefCount)
		GET_SET_PROPERTY(FileInfo^, Info, info)
		FileNode(String^ fileName) {
			info = gcnew FileInfo();
			fn = fileName;
			RefCount = 0;
		}
		inline void IncreamentRef() {
			Interlocked::Increment(RefCount);
		}
		inline void DecreamentRef() {
			Interlocked::Decrement(RefCount);
		}

	};
```

**Comment by billziss-gh** [comment]
Thanks for the explanation.

Suppose that as an alternative we use [`GCHandle`](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.gchandle(v=vs.110).aspx) to manage the .NET object's lifetime and keep the object from being CG'ed.

My C# is 10-years rusty. So excuse how this code looks:

```c++
// bad looking C#
struct Context
{
    Object FileNode;
    Object FileDesc;
};

...

Context context;
fs.Operations.Create(..., ref context);

...

// switching to C++, FullContext is of type (FSP_FSCTL_TRANSACT_FULL_CONTEXT *)
FullContext->UserContext = GCHandle::ToIntPtr(GCHandle::Alloc(context.FileNode));
FullContext->UserContext2 = GCHandle::ToIntPtr(GCHandle::Alloc(context.FileDesc));
```

At a later time we could do:

```
Context context;
context.FileNode = GCHandle::FromIntPtr(FullContext->UserContext)->Target;
context.FileDesc = GCHandle::FromIntPtr(FullContext->UserContext)->Target;
```

Would that not eliminate the need for the dictionary completely?

**Comment by yogendersolanki91** [comment]
> My C# is 10-years rusty

I believe everyone should have this kind of rusty knowledge .  💯 

> Suppose that as an alternative we use GCHandle to manage the .NET object's lifetime and keep the object from being CG'ed

Nice idea, We can do this. Thanks for pointing..

**Comment by billziss-gh** [comment]
>> My C# is 10-years rusty
> I believe everyone should have this kind of rusty knowledge . 💯

Thanks although I am going to have to reread some C# and C++/CLI materials to get myself up to speed.

**Comment by billziss-gh** [comment]
Closing this as we have eliminated FileNodeCollection.
